;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "denemo"
        "frescobaldi"
        "lilypond"
        "guile-hoot"
        "glfw"
        "gnuplot"
        "emacs-org-roam"
        "emacs-evil-collection"
        "neovim"
        "ripgrep"
        "emacs-magit"
        "rust-cargo"
        "rust"
        "git"
        "emacs-dap-mode"
        "emacs-lsp-mode"
        "emacs-lsp-ui"
        "emacs-next"
        "emacs"
        "emacs-guix"
        "sbcl"
        "emacs-web-mode"
        "emacs-rainbow-delimiters"
        "emacs-org"
        "emacs-paredit"
        "emacs-geiser-guile"
        "emacs-geiser"
        "gcc-toolchain"
        "emacs-corfu"
        "emacs-embark"
        "emacs-consult"
        "emacs-marginalia"
        "emacs-vertico"
        "kakoune"
        "emacs-doom-themes"
        "emacs-hydra"
        "emacs-solaire-mode"
        "emacs-buttercup"
        "emacs-which-key"
        "emacs-evil-surround"
        "emacs-evil"
        "emacs-orderless"
        "emacs-go-mode"
        "emacs-general"
        "emacs-mood-line"
        "nss-certs"
        "guile-next"
        "ghc"
        "guile-fibers"
        "make"
        "guile"
        "go"
        "openssl"
        "font-fira-mono"
        "font-fira-code"
        "font-go"
        "glibc-locales"))
